services:
  postgres:
    container_name: litink-dev-postgres
    ports:
      - "${DEV_POSTGRES_PORT}:5432"
    volumes:
      - litink-dev-pgdata:/var/lib/postgresql/data

  minio:
    container_name: litink-dev-minio
    ports:
      - "${DEV_MINIO_API_PORT}:9000"
      - "${DEV_MINIO_CONSOLE_PORT}:9001"
    volumes:
      - litink-dev-minio-data:/data

  redis:
    container_name: litink-dev-redis
    ports:
      - "${DEV_REDIS_PORT}:6379"
    volumes:
      - litink-dev-redis-data:/data

  backend:
    container_name: litink-dev-backend
    ports:
      - "${DEV_BACKEND_PORT}:8000"
    env_file:
      - ./backend/.envs/.env.dev

  frontend:
    container_name: litink-dev-frontend
    ports:
      - "${DEV_FRONTEND_PORT}:5173"
    environment:
      - VITE_API_URL=http://localhost:${DEV_BACKEND_PORT}

  celery-worker:
    container_name: litink-dev-celery-worker
    env_file:
      - ./backend/.envs/.env.dev

  celery-beat:
    container_name: litink-dev-celery-beat
    env_file:
      - ./backend/.envs/.env.dev

volumes:
  litink-dev-pgdata:
  litink-dev-minio-data:
  litink-dev-redis-data:
