[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://litinkapp.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Custom domain configuration
[[redirects]]
  from = "https://ni-scholar.com/*"
  to = "https://litink.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.ni-scholar.com/*"
  to = "https://litink.com/:splat"
  status = 301
  force = true