"""
OAuth CSRF state store — per-request, single-use, TTL-bound.

This module provides a lightweight in-memory store for OAuth state parameters.
It is designed for the current single-worker / local / staging runtime.

**Production note:** Replace this in-memory store with a Redis-backed
implementation (e.g. using the existing `app.core.services.redis.RedisService`)
before deploying to a multi-worker or horizontally-scaled production
environment.  The in-memory store will not share state across workers.

Design:
- Each state value is a cryptographically random token (generated by the
  caller via `secrets.token_urlsafe`).
- `store_state(state, ttl_s)` records the token with a TTL (default 600 s).
- `consume_state(state)` atomically validates and removes the token,
  enforcing single-use semantics.  Returns True on success, False on
  mismatch / expiry / replay.
- A background janitor task periodically evicts expired entries so the
  dict does not grow unboundedly.
"""

from __future__ import annotations

import asyncio
import time
from typing import Dict

from app.core.logging import get_logger

logger = get_logger()

# Default TTL for an OAuth state token (10 minutes).
DEFAULT_STATE_TTL_S = 600

# How often the janitor sweeps expired entries.
_JANITOR_INTERVAL_S = 120


class OAuthStateStore:
    """In-memory OAuth state store with TTL and single-use semantics."""

    def __init__(self) -> None:
        # state_value -> expiry (monotonic seconds)
        self._store: Dict[str, float] = {}
        self._janitor_task: asyncio.Task | None = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def store_state(self, state: str, ttl_s: int = DEFAULT_STATE_TTL_S) -> None:
        """Record *state* with the given TTL (seconds)."""
        self._store[state] = time.monotonic() + ttl_s
        logger.debug("OAuth state stored (ttl=%ds)", ttl_s)

    def consume_state(self, state: str) -> bool:
        """Validate and consume *state*.

        Returns True if the state was present and not expired (single-use —
        the entry is removed on success).  Returns False for missing,
        expired, or already-consumed tokens.
        """
        expiry = self._store.get(state)
        if expiry is None:
            logger.warning("OAuth state not found (missing or already consumed)")
            return False

        if time.monotonic() > expiry:
            # Expired — clean up and reject.
            del self._store[state]
            logger.warning("OAuth state expired")
            return False

        # Valid — consume (single-use).
        del self._store[state]
        logger.debug("OAuth state consumed successfully")
        return True

    # ------------------------------------------------------------------
    # Janitor (background expiry cleanup)
    # ------------------------------------------------------------------

    async def _janitor_loop(self) -> None:
        """Periodically evict expired entries."""
        while True:
            await asyncio.sleep(_JANITOR_INTERVAL_S)
            self._evict_expired()

    def _evict_expired(self) -> None:
        now = time.monotonic()
        expired = [s for s, exp in self._store.items() if now > exp]
        for s in expired:
            del self._store[s]
        if expired:
            logger.debug("OAuth state janitor evicted %d expired entries", len(expired))

    def start_janitor(self) -> None:
        """Start the background janitor task (idempotent)."""
        if self._janitor_task is None or self._janitor_task.done():
            self._janitor_task = asyncio.create_task(self._janitor_loop())
            logger.debug("OAuth state janitor started")

    async def stop_janitor(self) -> None:
        """Cancel the background janitor task."""
        if self._janitor_task and not self._janitor_task.done():
            self._janitor_task.cancel()
            try:
                await self._janitor_task
            except asyncio.CancelledError:
                pass
            logger.debug("OAuth state janitor stopped")

    # ------------------------------------------------------------------
    # Test / introspection helpers
    # ------------------------------------------------------------------

    def __len__(self) -> int:
        return len(self._store)

    def clear(self) -> None:
        self._store.clear()


# Module-level singleton — one store per process.
oauth_state_store = OAuthStateStore()
