"""add activation_token_hash and activation_token_expires_at to user

Revision ID: 240f2d0ba13d
Revises: c1d2e3f4g5h6
Create Date: 2026-06-11 08:40:55.003516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '240f2d0ba13d'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4g5h6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audiobook_chapters', 'error_message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('audiobooks', 'error_message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('ix_credit_failures_status'), table_name='credit_failures')
    op.drop_constraint(op.f('promo_codes_code_key'), 'promo_codes', type_='unique')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.alter_column('trailer_generations', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('user', sa.Column('activation_token_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))
    op.add_column('user', sa.Column('activation_token_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_activation_token_hash'), 'user', ['activation_token_hash'], unique=False)
    op.drop_index(op.f('ix_user_downloads_downloaded_at'), table_name='user_downloads')
    op.alter_column('video_generations', 'error_message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_generations', 'error_message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('ix_user_downloads_downloaded_at'), 'user_downloads', ['downloaded_at'], unique=False)
    op.drop_index(op.f('ix_user_activation_token_hash'), table_name='user')
    op.drop_column('user', 'activation_token_expires_at')
    op.drop_column('user', 'activation_token_hash')
    op.alter_column('trailer_generations', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=False)
    op.create_unique_constraint(op.f('promo_codes_code_key'), 'promo_codes', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_credit_failures_status'), 'credit_failures', ['status'], unique=False)
    op.alter_column('audiobooks', 'error_message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audiobook_chapters', 'error_message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
