"""remove_supabase_add_models_fix_meta

Revision ID: 281b2c1f4805
Revises: 844cec9746de
Create Date: 2025-12-03 03:08:15.736484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '281b2c1f4805'
down_revision: Union[str, Sequence[str], None] = '844cec9746de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_alerts_alert_type'), 'admin_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_admin_alerts_severity'), 'admin_alerts', ['severity'], unique=False)
    op.create_table('admin_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('setting_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('setting_value', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_settings_setting_key'), 'admin_settings', ['setting_key'], unique=True)
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criteria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rarity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merge_operations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('video_generation_id', sa.UUID(), nullable=True),
    sa.Column('merge_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('input_sources', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('ffmpeg_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('merge_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preview_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('video_file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merge_operations_user_id'), 'merge_operations', ['user_id'], unique=False)
    op.create_index(op.f('ix_merge_operations_video_generation_id'), 'merge_operations', ['video_generation_id'], unique=False)
    op.create_table('nfts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('tx_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfts_asset_id'), 'nfts', ['asset_id'], unique=True)
    op.create_index(op.f('ix_nfts_owner_id'), 'nfts', ['owner_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_book_id'), 'quizzes', ['book_id'], unique=False)
    op.create_index(op.f('ix_quizzes_chapter_id'), 'quizzes', ['chapter_id'], unique=False)
    op.create_table('pipeline_steps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('video_generation_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('step_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['video_generation_id'], ['video_generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_steps_video_generation_id'), 'pipeline_steps', ['video_generation_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'badge_id')
    )
    op.create_table('video_segments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('video_generation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('scene_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scene_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('dialogue_count', sa.Integer(), nullable=False),
    sa.Column('action_count', sa.Integer(), nullable=False),
    sa.Column('camera_movements', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('character_names', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_length', sa.Integer(), nullable=True),
    sa.Column('target_duration', sa.Float(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['video_generation_id'], ['video_generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_segments_user_id'), 'video_segments', ['user_id'], unique=False)
    op.create_index(op.f('ix_video_segments_video_generation_id'), 'video_segments', ['video_generation_id'], unique=False)
    op.add_column('image_generations', sa.Column('script_id', sa.UUID(), nullable=True))
    op.add_column('image_generations', sa.Column('chapter_id', sa.UUID(), nullable=True))
    op.add_column('image_generations', sa.Column('scene_number', sa.Integer(), nullable=True))
    op.add_column('image_generations', sa.Column('progress', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_image_generations_chapter_id'), 'image_generations', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_image_generations_script_id'), 'image_generations', ['script_id'], unique=False)
    op.add_column('learning_content', sa.Column('tavus_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('learning_content', sa.Column('generation_progress', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('learning_content', sa.Column('tavus_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('video_generations', sa.Column('can_resume', sa.Boolean(), nullable=False))
    op.add_column('video_generations', sa.Column('retry_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_generations', 'retry_count')
    op.drop_column('video_generations', 'can_resume')
    op.drop_column('learning_content', 'tavus_response')
    op.drop_column('learning_content', 'generation_progress')
    op.drop_column('learning_content', 'tavus_url')
    op.drop_index(op.f('ix_image_generations_script_id'), table_name='image_generations')
    op.drop_index(op.f('ix_image_generations_chapter_id'), table_name='image_generations')
    op.drop_column('image_generations', 'progress')
    op.drop_column('image_generations', 'scene_number')
    op.drop_column('image_generations', 'chapter_id')
    op.drop_column('image_generations', 'script_id')
    op.drop_index(op.f('ix_video_segments_video_generation_id'), table_name='video_segments')
    op.drop_index(op.f('ix_video_segments_user_id'), table_name='video_segments')
    op.drop_table('video_segments')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_pipeline_steps_video_generation_id'), table_name='pipeline_steps')
    op.drop_table('pipeline_steps')
    op.drop_index(op.f('ix_quizzes_chapter_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_book_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_nfts_owner_id'), table_name='nfts')
    op.drop_index(op.f('ix_nfts_asset_id'), table_name='nfts')
    op.drop_table('nfts')
    op.drop_index(op.f('ix_merge_operations_video_generation_id'), table_name='merge_operations')
    op.drop_index(op.f('ix_merge_operations_user_id'), table_name='merge_operations')
    op.drop_table('merge_operations')
    op.drop_table('badges')
    op.drop_index(op.f('ix_admin_settings_setting_key'), table_name='admin_settings')
    op.drop_table('admin_settings')
    op.drop_index(op.f('ix_admin_alerts_severity'), table_name='admin_alerts')
    op.drop_index(op.f('ix_admin_alerts_alert_type'), table_name='admin_alerts')
    op.drop_table('admin_alerts')
    # ### end Alembic commands ###
