"""Add fields to audio_generations table

Revision ID: 561296530fca
Revises: 281b2c1f4805
Create Date: 2025-12-03 07:26:04.798503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '561296530fca'
down_revision: Union[str, Sequence[str], None] = '281b2c1f4805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_generations', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('audio_generations', sa.Column('chapter_id', sa.UUID(), nullable=True))
    op.add_column('audio_generations', sa.Column('script_id', sa.UUID(), nullable=True))
    op.add_column('audio_generations', sa.Column('sequence_order', sa.Integer(), nullable=True))
    op.add_column('audio_generations', sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('audio_generations', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('audio_generations', sa.Column('audio_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True))
    op.create_index(op.f('ix_audio_generations_chapter_id'), 'audio_generations', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_audio_generations_script_id'), 'audio_generations', ['script_id'], unique=False)
    op.create_index(op.f('ix_audio_generations_user_id'), 'audio_generations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_generations_user_id'), table_name='audio_generations')
    op.drop_index(op.f('ix_audio_generations_script_id'), table_name='audio_generations')
    op.drop_index(op.f('ix_audio_generations_chapter_id'), table_name='audio_generations')
    op.drop_column('audio_generations', 'audio_metadata')
    op.drop_column('audio_generations', 'error_message')
    op.drop_column('audio_generations', 'model_id')
    op.drop_column('audio_generations', 'sequence_order')
    op.drop_column('audio_generations', 'script_id')
    op.drop_column('audio_generations', 'chapter_id')
    op.drop_column('audio_generations', 'user_id')
    # ### end Alembic commands ###
