"""Add preferred_mode

Revision ID: 65a1778a86c7
Revises: b40779076bc2
Create Date: 2025-12-04 05:11:00.981541

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "65a1778a86c7"
down_revision: Union[str, Sequence[str], None] = "b40779076bc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "preferred_mode",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="explorer",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "preferred_mode")
    # ### end Alembic commands ###
