"""add_project_and_artifact_models

Revision ID: 66a1aa9f0f52
Revises: 65a1778a86c7
Create Date: 2025-12-09 03:57:48.948112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66a1aa9f0f52'
down_revision: Union[str, Sequence[str], None] = '65a1778a86c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_type', postgresql.ENUM('ENTERTAINMENT', 'TRAINING', 'ADVERT', 'MUSIC_VIDEO', name='project_type'), nullable=False),
    sa.Column('workflow_mode', postgresql.ENUM('EXPLORER', 'CREATOR', name='workflow_mode'), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'GENERATING', 'REVIEW', 'COMPLETED', 'PUBLISHED', name='project_status'), nullable=False),
    sa.Column('input_prompt', sa.TEXT(), nullable=True),
    sa.Column('source_material_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_step', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipeline_steps', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('artifact_type', postgresql.ENUM('PLOT', 'SCRIPT', 'STORYBOARD', 'IMAGE', 'AUDIO', 'VIDEO', 'DOCUMENT_SUMMARY', name='artifact_type'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('parent_artifact_id', sa.UUID(), nullable=True),
    sa.Column('generated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_parent_artifact_id'), 'artifacts', ['parent_artifact_id'], unique=False)
    op.create_index(op.f('ix_artifacts_project_id'), 'artifacts', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_project_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_parent_artifact_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
