"""add_emotional_map_to_scripts

Revision ID: 6853163b0db2
Revises: 6ae04d08e2ae
Create Date: 2026-01-20 00:21:04.446320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6853163b0db2'
down_revision: Union[str, Sequence[str], None] = '6ae04d08e2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('emotional_map', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'emotional_map')
    # ### end Alembic commands ###
