"""add_accent_to_characters

Revision ID: 6ae04d08e2ae
Revises: i4j5k6l7m8n9
Create Date: 2026-01-19 21:33:35.053024

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6ae04d08e2ae"
down_revision: Union[str, Sequence[str], None] = "i4j5k6l7m8n9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters",
        sa.Column(
            "accent",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="neutral",
        ),
    )
    op.add_column(
        "characters",
        sa.Column(
            "voice_characteristics", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "characters",
        sa.Column(
            "voice_gender",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="auto",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "voice_gender")
    op.drop_column("characters", "voice_characteristics")
    op.drop_column("characters", "accent")
    # ### end Alembic commands ###
