"""Add UserOAuth table

Revision ID: 717fed1bf007
Revises: 72e0e3b08f17
Create Date: 2025-12-30 04:35:27.393762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '717fed1bf007'
down_revision: Union[str, Sequence[str], None] = '72e0e3b08f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_oauth',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'APPLE', 'MICROSOFT', name='oauthprovider'), nullable=False),
    sa.Column('provider_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='unique_provider_user')
    )
    op.create_index(op.f('ix_user_oauth_provider'), 'user_oauth', ['provider'], unique=False)
    op.create_index(op.f('ix_user_oauth_provider_user_id'), 'user_oauth', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_user_oauth_user_id'), 'user_oauth', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_oauth_user_id'), table_name='user_oauth')
    op.drop_index(op.f('ix_user_oauth_provider_user_id'), table_name='user_oauth')
    op.drop_index(op.f('ix_user_oauth_provider'), table_name='user_oauth')
    op.drop_table('user_oauth')
    # ### end Alembic commands ###
