"""add_onboarding_completed_and_optional_fields

Revision ID: 72e0e3b08f17
Revises: 85a6eac2285a
Create Date: 2025-12-28 21:11:10.487488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "72e0e3b08f17"
down_revision: Union[str, Sequence[str], None] = "85a6eac2285a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server_default for existing rows
    op.add_column(
        "user",
        sa.Column(
            "onboarding_completed", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # Remove server_default so new rows need explicit value
    op.alter_column("user", "onboarding_completed", server_default=None)
    op.alter_column(
        "user",
        "display_name",
        existing_type=sa.VARCHAR(length=12),
        type_=sqlmodel.sql.sqltypes.AutoString(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "user", "first_name", existing_type=sa.VARCHAR(length=30), nullable=True
    )
    op.alter_column(
        "user", "last_name", existing_type=sa.VARCHAR(length=30), nullable=True
    )
    op.alter_column(
        "user",
        "security_question",
        existing_type=postgresql.ENUM(
            "MOTHER_MAIDEN_NAME",
            "CHILDHOOD_FRIEND",
            "FAVORITE_COLOUR",
            "BIRTH_CITY",
            name="securityquestionsschema",
        ),
        nullable=True,
    )
    op.alter_column(
        "user", "security_answer", existing_type=sa.VARCHAR(length=30), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "security_answer", existing_type=sa.VARCHAR(length=30), nullable=False
    )
    op.alter_column(
        "user",
        "security_question",
        existing_type=postgresql.ENUM(
            "MOTHER_MAIDEN_NAME",
            "CHILDHOOD_FRIEND",
            "FAVORITE_COLOUR",
            "BIRTH_CITY",
            name="securityquestionsschema",
        ),
        nullable=False,
    )
    op.alter_column(
        "user", "last_name", existing_type=sa.VARCHAR(length=30), nullable=False
    )
    op.alter_column(
        "user", "first_name", existing_type=sa.VARCHAR(length=30), nullable=False
    )
    op.alter_column(
        "user",
        "display_name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
        type_=sa.VARCHAR(length=12),
        existing_nullable=True,
    )
    op.drop_column("user", "onboarding_completed")
    # ### end Alembic commands ###
