"""add progress fields to book

Revision ID: 7ebcb2766008
Revises: cd2c0f07c718
Create Date: 2025-12-09 08:04:13.218589

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7ebcb2766008"
down_revision: Union[str, Sequence[str], None] = "cd2c0f07c718"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books",
        sa.Column(
            "progress", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
    )
    op.add_column(
        "books",
        sa.Column(
            "progress_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "progress_message")
    op.drop_column("books", "progress")
    # ### end Alembic commands ###
