"""initial_migration

Revision ID: 8383a6788dcb
Revises:
Create Date: 2025-12-02 07:34:45.647178

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8383a6788dcb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # User table (was previously managed outside alembic)
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "display_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("avatar_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "first_name", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False
        ),
        sa.Column(
            "middle_name", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True
        ),
        sa.Column(
            "last_name", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False
        ),
        sa.Column("roles", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column(
            "security_question",
            sqlmodel.sql.sqltypes.AutoString(length=30),
            nullable=False,
        ),
        sa.Column(
            "security_answer",
            sqlmodel.sql.sqltypes.AutoString(length=30),
            nullable=False,
        ),
        sa.Column("account_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("failed_login_attempts", sa.SmallInteger(), nullable=False),
        sa.Column(
            "last_failed_login", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("display_name"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "books",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cover_image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("book_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_chapters", sa.Integer(), nullable=False),
        sa.Column("estimated_duration", sa.Integer(), nullable=True),
        sa.Column("difficulty", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.TEXT()), nullable=True),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("has_sections", sa.Boolean(), nullable=False),
        sa.Column("structure_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_books_user_id"), "books", ["user_id"], unique=False)
    op.create_table(
        "character_archetypes",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "traits",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "typical_roles",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "example_characters", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "image_records",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("image_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "scene_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("character_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("thumbnail_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("image_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("script_id", sa.UUID(), nullable=True),
        sa.Column("chapter_id", sa.UUID(), nullable=True),
        sa.Column("scene_number", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("generation_time_seconds", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_image_records_chapter_id"),
        "image_records",
        ["chapter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_image_records_script_id"), "image_records", ["script_id"], unique=False
    )
    op.create_index(
        op.f("ix_image_records_user_id"), "image_records", ["user_id"], unique=False
    )
    op.create_table(
        "plot_overviews",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("logline", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "themes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=True,
        ),
        sa.Column("story_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "script_story_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("genre", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("audience", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("setting", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "generation_method", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("model_used", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_plot_overviews_book_id"), "plot_overviews", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_plot_overviews_user_id"), "plot_overviews", ["user_id"], unique=False
    )
    op.create_table(
        "profiles",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("avatar_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("website", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "social_links",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiles_user_id"), "profiles", ["user_id"], unique=True)
    op.create_table(
        "subscription_history",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("from_tier", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("to_tier", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("from_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("to_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("stripe_event_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_history_user_id"),
        "subscription_history",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "usage_logs",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=True),
        sa.Column("resource_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resource_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usage_logs_resource_type"),
        "usage_logs",
        ["resource_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_usage_logs_subscription_id"),
        "usage_logs",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_usage_logs_user_id"), "usage_logs", ["user_id"], unique=False
    )
    op.create_table(
        "user_subscriptions",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "tier",
            postgresql.ENUM("FREE", "BASIC", "PRO", name="subscription_tier"),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE",
                "CANCELLED",
                "EXPIRED",
                "PAST_DUE",
                "TRIALING",
                name="subscription_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "stripe_customer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "stripe_subscription_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("stripe_price_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "current_period_start", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column(
            "current_period_end", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("cancelled_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_subscriptions_stripe_customer_id"),
        "user_subscriptions",
        ["stripe_customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_subscriptions_stripe_subscription_id"),
        "user_subscriptions",
        ["stripe_subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_subscriptions_user_id"),
        "user_subscriptions",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "video_generations",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("chapter_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("script_id", sa.UUID(), nullable=True),
        sa.Column(
            "generation_status",
            postgresql.ENUM(
                "PENDING",
                "GENERATING_AUDIO",
                "AUDIO_COMPLETED",
                "GENERATING_IMAGES",
                "IMAGES_COMPLETED",
                "GENERATING_VIDEO",
                "VIDEO_COMPLETED",
                "MERGING_AUDIO",
                "APPLYING_LIPSYNC",
                "COMBINING",
                "COMPLETED",
                "FAILED",
                "RETRYING",
                name="video_generation_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "quality_tier",
            postgresql.ENUM(
                "FREE",
                "BASIC",
                "STANDARD",
                "STANDARD_2",
                "PRO",
                "MASTER",
                name="video_quality_tier",
            ),
            nullable=False,
        ),
        sa.Column("video_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("audio_task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "task_meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "script_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "audio_files",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "image_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "video_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "merge_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "lipsync_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_video_generations_chapter_id"),
        "video_generations",
        ["chapter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_video_generations_script_id"),
        "video_generations",
        ["script_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_video_generations_user_id"),
        "video_generations",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "audio_generations",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("video_generation_id", sa.UUID(), nullable=False),
        sa.Column(
            "audio_type",
            postgresql.ENUM(
                "NARRATOR",
                "CHARACTER",
                "SOUND_EFFECTS",
                "BACKGROUND_MUSIC",
                name="audio_type",
            ),
            nullable=False,
        ),
        sa.Column("scene_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("character_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("text_content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("voice_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("audio_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["video_generation_id"],
            ["video_generations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audio_generations_video_generation_id"),
        "audio_generations",
        ["video_generation_id"],
        unique=False,
    )
    op.create_table(
        "chapter_scripts",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("chapter_id", sa.UUID(), nullable=False),
        sa.Column("plot_overview_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("plot_enhanced", sa.Boolean(), nullable=False),
        sa.Column("character_enhanced", sa.Boolean(), nullable=False),
        sa.Column(
            "scenes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "acts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "beats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "character_details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "character_arcs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "generation_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plot_overview_id"],
            ["plot_overviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chapter_scripts_chapter_id"),
        "chapter_scripts",
        ["chapter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chapter_scripts_plot_overview_id"),
        "chapter_scripts",
        ["plot_overview_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chapter_scripts_user_id"), "chapter_scripts", ["user_id"], unique=False
    )
    op.create_table(
        "characters",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("plot_overview_id", sa.UUID(), nullable=False),
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("character_arc", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "physical_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("personality", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "archetypes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=True,
        ),
        sa.Column("want", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("need", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("lie", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ghost", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "image_generation_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "image_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plot_overview_id"],
            ["plot_overviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_characters_book_id"), "characters", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_characters_plot_overview_id"),
        "characters",
        ["plot_overview_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_characters_user_id"), "characters", ["user_id"], unique=False
    )
    op.create_table(
        "image_generations",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("video_generation_id", sa.UUID(), nullable=False),
        sa.Column("image_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scene_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("character_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("shot_index", sa.Integer(), nullable=False),
        sa.Column(
            "scene_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("image_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("text_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("style", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("thumbnail_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("generation_time_seconds", sa.Float(), nullable=True),
        sa.Column("sequence_order", sa.Integer(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["video_generation_id"],
            ["video_generations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_image_generations_video_generation_id"),
        "image_generations",
        ["video_generation_id"],
        unique=False,
    )
    op.create_table(
        "sections",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("section_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("section_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sections_book_id"), "sections", ["book_id"], unique=False)
    op.create_table(
        "chapters",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("chapter_number", sa.Integer(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chapters_book_id"), "chapters", ["book_id"], unique=False)
    op.create_index(
        op.f("ix_chapters_section_id"), "chapters", ["section_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chapters_section_id"), table_name="chapters")
    op.drop_index(op.f("ix_chapters_book_id"), table_name="chapters")
    op.drop_table("chapters")
    op.drop_index(op.f("ix_sections_book_id"), table_name="sections")
    op.drop_table("sections")
    op.drop_index(
        op.f("ix_image_generations_video_generation_id"), table_name="image_generations"
    )
    op.drop_table("image_generations")
    op.drop_index(op.f("ix_characters_user_id"), table_name="characters")
    op.drop_index(op.f("ix_characters_plot_overview_id"), table_name="characters")
    op.drop_index(op.f("ix_characters_book_id"), table_name="characters")
    op.drop_table("characters")
    op.drop_index(op.f("ix_chapter_scripts_user_id"), table_name="chapter_scripts")
    op.drop_index(
        op.f("ix_chapter_scripts_plot_overview_id"), table_name="chapter_scripts"
    )
    op.drop_index(op.f("ix_chapter_scripts_chapter_id"), table_name="chapter_scripts")
    op.drop_table("chapter_scripts")
    op.drop_index(
        op.f("ix_audio_generations_video_generation_id"), table_name="audio_generations"
    )
    op.drop_table("audio_generations")
    op.drop_index(op.f("ix_video_generations_user_id"), table_name="video_generations")
    op.drop_index(
        op.f("ix_video_generations_script_id"), table_name="video_generations"
    )
    op.drop_index(
        op.f("ix_video_generations_chapter_id"), table_name="video_generations"
    )
    op.drop_table("video_generations")
    op.drop_index(
        op.f("ix_user_subscriptions_user_id"), table_name="user_subscriptions"
    )
    op.drop_index(
        op.f("ix_user_subscriptions_stripe_subscription_id"),
        table_name="user_subscriptions",
    )
    op.drop_index(
        op.f("ix_user_subscriptions_stripe_customer_id"),
        table_name="user_subscriptions",
    )
    op.drop_table("user_subscriptions")
    op.drop_index(op.f("ix_usage_logs_user_id"), table_name="usage_logs")
    op.drop_index(op.f("ix_usage_logs_subscription_id"), table_name="usage_logs")
    op.drop_index(op.f("ix_usage_logs_resource_type"), table_name="usage_logs")
    op.drop_table("usage_logs")
    op.drop_index(
        op.f("ix_subscription_history_user_id"), table_name="subscription_history"
    )
    op.drop_table("subscription_history")
    op.drop_index(op.f("ix_profiles_user_id"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_plot_overviews_user_id"), table_name="plot_overviews")
    op.drop_index(op.f("ix_plot_overviews_book_id"), table_name="plot_overviews")
    op.drop_table("plot_overviews")
    op.drop_index(op.f("ix_image_records_user_id"), table_name="image_records")
    op.drop_index(op.f("ix_image_records_script_id"), table_name="image_records")
    op.drop_index(op.f("ix_image_records_chapter_id"), table_name="image_records")
    op.drop_table("image_records")
    op.drop_table("character_archetypes")
    op.drop_index(op.f("ix_books_user_id"), table_name="books")
    op.drop_table("books")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
