"""add_subscription_tier_fields

Revision ID: 85a6eac2285a
Revises: 8ec4550c4e62
Create Date: 2025-12-27 08:21:53.631147

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "85a6eac2285a"
down_revision: Union[str, Sequence[str], None] = "8ec4550c4e62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns with server defaults to handle existing rows
    op.add_column(
        "user_subscriptions",
        sa.Column(
            "monthly_video_limit", sa.Integer(), nullable=False, server_default="2"
        ),
    )
    op.add_column(
        "user_subscriptions",
        sa.Column(
            "video_quality",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="720p",
        ),
    )
    op.add_column(
        "user_subscriptions",
        sa.Column("has_watermark", sa.Boolean(), nullable=False, server_default="true"),
    )
    op.add_column(
        "user_subscriptions",
        sa.Column(
            "videos_generated_this_period",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    op.add_column(
        "user_subscriptions",
        sa.Column(
            "next_billing_date", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_subscriptions", "next_billing_date")
    op.drop_column("user_subscriptions", "videos_generated_this_period")
    op.drop_column("user_subscriptions", "has_watermark")
    op.drop_column("user_subscriptions", "video_quality")
    op.drop_column("user_subscriptions", "monthly_video_limit")
    # ### end Alembic commands ###
