"""add_subscription_tiers

Revision ID: 8ec4550c4e62
Revises: a1b2c3d4e5f6
Create Date: 2025-12-27 05:22:17.633332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8ec4550c4e62"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually adding new enum values since Alembic autogenerate doesn't handle Postgres Enums well
    op.execute("ALTER TYPE subscription_tier ADD VALUE 'premium'")
    op.execute("ALTER TYPE subscription_tier ADD VALUE 'professional'")
    op.execute("ALTER TYPE subscription_tier ADD VALUE 'enterprise'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
