"""add_creative_directive_to_plot_overview

Revision ID: 9c28c4950e72
Revises: a9c9e98e80b7
Create Date: 2026-01-11 23:03:23.553122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c28c4950e72'
down_revision: Union[str, Sequence[str], None] = 'a9c9e98e80b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot_overviews', sa.Column('creative_directive', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plot_overviews', 'creative_directive')
    # ### end Alembic commands ###
