"""add_original_file_storage_path_to_books

Revision ID: cd2c0f07c718
Revises: 66a1aa9f0f52
Create Date: 2025-12-09 06:23:41.775461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd2c0f07c718'
down_revision: Union[str, Sequence[str], None] = '66a1aa9f0f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('original_file_storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'original_file_storage_path')
    # ### end Alembic commands ###
