"""add_entity_type_to_characters

Revision ID: e0bc180d1fa9
Revises: 521eee0937ac
Create Date: 2026-01-13 04:40:04.878026

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e0bc180d1fa9"
down_revision: Union[str, Sequence[str], None] = "521eee0937ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters",
        sa.Column(
            "entity_type",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="character",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "entity_type")
    # ### end Alembic commands ###
