"""Make video_generation_id optional in audio_generations

Revision ID: e7155472d336
Revises: 561296530fca
Create Date: 2025-12-03 07:39:53.087927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e7155472d336'
down_revision: Union[str, Sequence[str], None] = '561296530fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio_generations', 'video_generation_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio_generations', 'video_generation_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
