"""Add payment fields to books table

Revision ID: ef1dbf41e538
Revises: 532361aee3d5
Create Date: 2025-12-03 07:51:09.328676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ef1dbf41e538'
down_revision: Union[str, Sequence[str], None] = '532361aee3d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('stripe_checkout_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('books', sa.Column('stripe_payment_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('books', sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('books', sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'payment_status')
    op.drop_column('books', 'stripe_customer_id')
    op.drop_column('books', 'stripe_payment_intent_id')
    op.drop_column('books', 'stripe_checkout_session_id')
    # ### end Alembic commands ###
