"""Refactor services and add LearningContent

Revision ID: fae90d574863
Revises: 8383a6788dcb
Create Date: 2025-12-02 15:56:36.494374

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = "fae90d574863"
down_revision: Union[str, Sequence[str], None] = "8383a6788dcb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "scripts",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("chapter_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("script_style", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("script", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("video_style", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "characters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "character_details", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "evaluation",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scripts_chapter_id"), "scripts", ["chapter_id"], unique=False
    )
    op.create_index(op.f("ix_scripts_user_id"), "scripts", ["user_id"], unique=False)
    op.create_table(
        "book_embeddings",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("content_chunk", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_size", sa.Integer(), nullable=False),
        sa.Column("chunk_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_book_embeddings_book_id"), "book_embeddings", ["book_id"], unique=False
    )
    op.create_table(
        "chapter_embeddings",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("chapter_id", sa.UUID(), nullable=False),
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("content_chunk", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_size", sa.Integer(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chapter_embeddings_book_id"),
        "chapter_embeddings",
        ["book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chapter_embeddings_chapter_id"),
        "chapter_embeddings",
        ["chapter_id"],
        unique=False,
    )
    op.create_table(
        "learning_content",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("chapter_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_content_chapter_id"),
        "learning_content",
        ["chapter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_content_user_id"),
        "learning_content",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "characters",
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "image_generations",
        sa.Column("character_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("image_generations", sa.Column("user_id", sa.UUID(), nullable=True))
    op.add_column(
        "image_generations",
        sa.Column("aspect_ratio", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column(
        "image_generations",
        "video_generation_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.create_index(
        op.f("ix_image_generations_user_id"),
        "image_generations",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_image_generations_user_id"), table_name="image_generations")
    op.alter_column(
        "image_generations",
        "video_generation_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.drop_column("image_generations", "aspect_ratio")
    op.drop_column("image_generations", "user_id")
    op.drop_column("image_generations", "character_id")
    op.drop_column("characters", "status")
    op.drop_index(op.f("ix_learning_content_user_id"), table_name="learning_content")
    op.drop_index(op.f("ix_learning_content_chapter_id"), table_name="learning_content")
    op.drop_table("learning_content")
    op.drop_index(
        op.f("ix_chapter_embeddings_chapter_id"), table_name="chapter_embeddings"
    )
    op.drop_index(
        op.f("ix_chapter_embeddings_book_id"), table_name="chapter_embeddings"
    )
    op.drop_table("chapter_embeddings")
    op.drop_index(op.f("ix_book_embeddings_book_id"), table_name="book_embeddings")
    op.drop_table("book_embeddings")
    op.drop_index(op.f("ix_scripts_user_id"), table_name="scripts")
    op.drop_index(op.f("ix_scripts_chapter_id"), table_name="scripts")
    op.drop_table("scripts")
    # ### end Alembic commands ###
